name: Android CI

on:
  push:
    branches: [ "feature/Kaspresso-tests-advanced" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64


      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
  unit-test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test

  instrumentation-test:
    needs: [ build ]
    runs-on: macos-11
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Kaspresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 23
          target: default
          arch: x64
          profile: Nexus 6
          script: ./gradlew connectedCheck