name: Android CI

on:
  push:
    branches: [ "feature/Kaspresso-tests-advanced" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  unit-test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test

  instrumentation-test:
    needs: [ unit-test ]
    runs-on: macos-11
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Kaspresso tests
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Nexus 6P
          script: ./gradlew connectedCheck