# Workflow name
name: Build
on:
  # When it will be triggered
  # And in which branch
  push:
    branches:
      - feature/Kaspresso-tests-advanced
  # Where will they run
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
