name: Android CI

on:
  push:
    branches:
      - kaspresso-tests-advanced

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle


      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew assembleDebug assembleDebugAndroidTest
  unit-test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test

  instrumentation-test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Kaspresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          target: default
          arch: x86_64
          profile: Nexus 6P
          script: ./gradlew connectedCheck
