name: CI

on:
  push:
    branches: [ "feature/Kaspresso-tests-advanced" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test

  instrumentation-test:
    needs: [ unit-test ]
    runs-on: macos-11
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Kaspresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86
          profile: Nexus 6
          emulator-build: 7425822
          script: ./gradlew connectedCheck
