# Workflow name
name: Build
on:
  # When it will be triggered
  # And in which branch
  push:
    branches:
      - feature/Kaspresso-tests-advanced
  # Where will they run
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build --scan
